services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      # NGINXのコンフィグファイルをホストOSから、ゲストOSに連結する
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # HTTPS用の証明書とキーをホストOSから、ゲストOSに連結する
      # - /home/yukkuri/certificates/yukkuri.me.crt:/etc/nginx/conf.d/yukkuri.me.crt:Z
      # - /home/yukkuri/certificates/yukkuri.me.key:/etc/nginx/conf.d/yukkuri.me.key:Z
      # NGINXのWebアプリ（index.html等）をホストOSから、ゲストOSに連結する
      - ./nginx/html:/var/www/html
    networks:
      - frontend
  # app:
  #   build: ./app
  #   networks:
  #     - frontend
  #     - backend
  # db:
  #   image: postgres
  #   networks:
  #     - backend

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24